### PR TITLE
Fixing the testharness to work when there are no tests.

### LINKED ISSUE #347: Testharness breaks when there are no tests to run

### PR DESCRIPTION
**Pull request by mithro**
Fixes #347 reported by Alan.

### CODE REVIEW

File: test/testharness_timing.js [hunk 1]
```diff
@@ -548,8 +568,14 @@
 
         var t = ts - raf_t0;
 
+        var endTime = testharness_timeline.endTime_;
+        // If we have no events paste t=0, endTime is going to be zero. Instead
```
Comment (dstoc) [inline test/testharness_timing.js:551]: Can't we just do this when endTime is 0?

Comment (mithro) [inline test/testharness_timing.js:551]: Yes, you are right. That makes this patch much similar.

**Comment by mithro** [comment]
PTAL.
