### PR TITLE
Add inline style hack fallback (fixes Safari)

### LINKED ISSUE #492: Attempting to override getter element style fails in Safari

### PR DESCRIPTION
**Pull request by alancutter**
This change provides an alternate patch for animated inline styles.
If replacing element.style with an AnimatedCSSStyleDeclaration is not allowed (which is the case for Safari) it will instead patch the existing inline style object methods to behave in a similar way.
Property getters and setters are not patched and will not function normally while under animation with this fallback.

Fixes #492

### CODE REVIEW

File: web-animations.js [hunk 1]
```diff
@@ -4948,55 +5002,69 @@ Compositor.prototype = {
...
+  if (target.style._webAnimationsStyleInitialised) {
+    return;
+  }
+  try {
     var animatedStyle = new AnimatedCSSStyleDeclaration(target);
     Object.defineProperty(target, 'style', configureDescriptor({
       get: function() { return animatedStyle; }
     }));
   }
+  catch (error) {
```
Comment (dstoc) [inline web-animations.js]: catch should be on the previous line: 
try {
} catch (...

**Comment by dstoc** [comment]
lgtm

File: web-animations.js (hunk 1 above)
Comment (alancutter) [inline web-animations.js]: Done.
